version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: booky
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: booky
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      API_URL: http://backend:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  db_data:
